### ISSUE TITLE
Plugin breaks the Admin Menu

### ISSUE THREAD

**Issue by Tangol** [webmods-croatia/oscplugin-usercf#1]
Please note that the plugin breaks the admin menu and also there is a problem with its styling.

![bug](https://user-images.githubusercontent.com/3336728/67602764-04357e80-f780-11e9-87f7-39f2ed6ea9ab.jpg)

Stock Osclass 3.8.0, Plugin v1.1.1, PHP 7.0.33, Firefox 70.

**Comment by webmods-croatia** [comment]
Seems like Bootstrap didn't load for some reason. Any errors in console?

**Comment by Tangol** [comment]
![bug2](https://user-images.githubusercontent.com/3336728/67623979-3ef8ee80-f834-11e9-9eee-392bd2873d23.jpg)

**Comment by webmods-croatia** [comment]
Have you downloaded the plugin fron Releases tab?

**Comment by Tangol** [comment]
Ohh, it works now.
At first I got it form the master branch.

The download from the releases section works fine.

Can be closed. Thanks!

**Comment by webmods-croatia** [comment]
No problem. :)

When you download the repo, not the release, the folder name is oscplugin-usercf instead of zo_usercf so assets can't be loaded.
